package main

import (
	"context"

	"github.com/aws/aws-lambda-go/lambda"
)

type AutoGenerated struct {
	Department string   `json:"department"`
	Categories []string `json:"categories"`
	Bins       []struct {
		Category string  `json:"category"`
		Type     string  `json:"type"`
		Price    float64 `json:"price"`
		Unit     string  `json:"unit"`
		Quantity int     `json:"quantity"`
	} `json:"bins"`
}

func HandleRequest(ctx context.Context, name MyEvent) (string, error) {

}

func main() {
	lambda.Start(HandleRequest)
}
